# https://docs.readthedocs.io/en/latest/config-file/index.html#configuration-file
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - source $HOME/.poetry/env
      - poetry install

